version: "2"
virtualmachines:
- name: kubernetes
  image: instruqt-hashicorp/kubernetes-base
  shell: /bin/bash
  machine_type: n1-standard-1
- name: terraform
  image: instruqt-hashicorp/hashistack-0-1-0
  shell: /bin/bash
  machine_type: g1-small
