# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
virtualmachines:
- name: vagrant
  image: instruqt-hashicorp/vagrant-2-2-4
  shell: /bin/bash
  machine_type: n1-standard-2
