# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
virtualmachines:
- name: kubernetes
  image: instruqt-hashicorp/kubernetes-base
  shell: /bin/bash
  machine_type: n1-standard-2
