# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
virtualmachines:
- name: gamma
  image: instruqt-hashicorp/hashistack-0-1-0
  shell: /bin/bash
  machine_type: g1-small
- name: alpha
  image: instruqt-hashicorp/hashistack-0-1-0
  shell: /bin/bash
  machine_type: g1-small
- name: beta
  image: instruqt-hashicorp/hashistack-0-1-0
  shell: /bin/bash
  machine_type: g1-small
