#!/bin/bash

which set-workdir
env

# Set workdir
set-workdir "/tmp/security/exercises/03-setup-upstream/files/app"

kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /tmp/security/exercises/03-setup-upstream/files/app